### ISSUE TITLE
Allow switching the refresh rate

### ISSUE THREAD

**Issue by carverhaines** [CappyT/g14control#1]
Would like to see changing the refresh rate to 60 Hz for some of the battery/low power plans.

**Comment by carverhaines** [comment]
Contains some possible useful info: https://superuser.com/questions/1184815/is-a-way-to-quickly-set-screen-refresh-rate
http://tools.taubenkorb.at/change-screen-resolution/
http://nircmd.nirsoft.net/

**Comment by carverhaines** [comment]
Can confirm that 
```
ChangeScreenResolution.exe /f=120 /d=0
and
ChangeScreenResolution.exe /f=60 /d=0
```
works for changing refresh rate.

Would need to include the ChangeScreenResolution.exe (only 26kb)

 Then something like this? (Not a python programmer, so I will leave that up to you @CappyT )

```
def get_refresh_rate():
    os.popen("ChangeScreenResolution.exe /l")
    # Then have to parse that output, looking for number between '@' and 'Hz'
    # Then:
    return current_refresh_rate

def set_refresh_rate(state, notification=True):
    current_refresh_rate = get_refresh_rate()
    os.popen("ChangeScreenResolution.exe /f=" + refresh_rate_requested + "/d=0 ")
```

**Comment by carverhaines** [comment]
In the meantime I've made myself 2 BAT files on the desktop I can click to change refresh rate:

120Hz.bat
`C:\ChangeScreenResolution.exe /f=120 /d=0`

and

60Hz.bat
`C:\ChangeScreenResolution.exe /f=60 /d=0`

:)

**Comment by CappyT** [comment]
Exceptional find, many many thanks for that!

I will add it asap, if you didn't already in your pull request.

**Comment by carverhaines** [comment]
No pull request, the code needs to be fleshed out a little bit more, that was just the general idea came up with.

**Comment by carverhaines** [comment]
For reference, changes were these commits:
5535c253aff1b1dff7b914d82be6fb33aea239c9
0c2a9c6143826a4cdd2d9e5adea4eea9a60cc513
1beb65470322d61488f419afce360539e82e9aed
