### ISSUE TITLE
Recent addition of running in debug mode breaks EXE

### ISSUE THREAD

**Issue by carverhaines** [CappyT/g14control#12]
Commit 6eef3ffa937446b98064bddae16d985f88a82783 where adding 'PYCHARM' debug mode breaks the compile exe with traceback error:
```
File G14 Control.pyw line 239
Raise Key Error from None
KeyError: 'PYCHARM'
```
Recommend removing, or fixing if truly necessary:
```
G14 Control.pyw line 239
-     if is_admin() or os.environ['PYCHARM']:  # If running as admin or in debug mode, launch program
+    if is_admin():  # If running as admin, launch program
```

Could be due to the fact I don't have PYCHARM running on my system, which most people will not.

**Comment by CappyT** [comment]
I kinda need that key, basically allows me to run the script without having to launch it as administrator when debugging ( this is very important, if i get uac, debugger detaches from the main process because this relaunches)

**Comment by carverhaines** [comment]
Test my PR in this, see if it helps. Otherwise just run Pycharm as administrator, then we'll never get asked for UAC. I've been doing that w/ IDLE when debugging.

**Comment by carverhaines** [comment]
Alternatively, we can put a `Debug: True` in the config file, then:
```
if is_admin() or config['Debug']:  # If running as admin or in debug mode, launch program
```

**Comment by carverhaines** [comment]
Updated this to use a true/false debug mode in config file. If you need to debug without UAC/Admin rights, just set to `true` in config.yaml.
PR #15
