### ISSUE TITLE
Update info in notification displayed when left clicking icon

### ISSUE THREAD

**Issue by carverhaines** [CappyT/g14control#19]
Current:
```
Current Config: Silent
Boost Active: True/False
AC: True/False
dGPU: True/False
```

Desired:
```
Plan: Silent
Boost: Enabled/Disabled
Power: AC Adapter/Battery
dGPU: Enabled/Disabled
Refresh Rate: 60Hz/120Hz
```

**Comment by CappyT** [comment]
There is a limit of total lines we can display in the windows notification. I will try to fit those anyway, let's see if it hits the limit or not.

**Comment by carverhaines** [comment]
I've already started a branch on this one

**Comment by carverhaines** [comment]
Actually, have at it, won't be able to work on it for a while
Yes, looks like 4 line max:
```
Plan: Silent
Boost: On/Off    dGPU: On/Off
Power: AC Adapter/Battery
Refresh Rate: 60Hz/120Hz
```

**Comment by carverhaines** [comment]
Put in Pull Request #20 that addresses this
