### ISSUE TITLE
Add functionality to adjust GPU overclock (similar to Armoury Crate)

### ISSUE THREAD

**Issue by zandm7** [CappyT/g14control#31]
As it stands I'm already pretty much ready to replace Armoury Crate with G14Control, but the only thing I've noticed missing (functionality-wise) is the ability to adjust the GPU overclock the way Armoury Crate's Manual mode allows.

Also, as a clarifying question: Does G14Control's "Extreme" mode retain the GPU overclock from Armoury Crate's "Turbo" mode?

**Comment by carverhaines** [comment]
Your second question first:
Yes, by default the 'Extreme' plan uses the turbo Armoury crate mode, and I can confirm by testing this does apply the GPU & CPU overclock. 

Currently there is not a setting to adjust the GPU overclock, other than one of using Armory Crates predetermined plans. However G14Control can enable or disable CPU boost.
