### ISSUE TITLE
Support for other models 

### ISSUE THREAD

**Issue by EmeraldRod** [CappyT/g14control#36]
for example a gtx 1650 R7 4800hs just an example

**Comment by jQubz** [comment]
This should be compatible with all existing models. Can I ask you why you think it's not compatible with R7/1650 model?

**Comment by EmeraldRod** [comment]
So I used to have the "G14control r2" version of the program, and in the zip file came other than the .exe and the .yml file, also a few other files including a .bat file which runs the restartGPU.ps1 file. In that file it has some line with text saying "2080". The dGPU -> OFF option didn't work until I replaced that line to say "1650" instead of the default "2080". So now in this 0.1 version, the dGPU -> OFF doesn't do anything, and the only files included in the zip are they .yml and the .exe.

**Comment by jQubz** [comment]
Oh yeah, you're absolutely right. Problem is that G14 Control r2 is a completely different project and this disabling GPU feature is implemented only there AFAIR. Therefore you should make an issue in the other project :)

I believe it just looks for unique identifier of particular GPU model there, so theoretically should be easy to implement it to support 1650, 1650ti or other models.
