### ISSUE TITLE
Remember last state between reboots

### ISSUE THREAD

**Issue by carverhaines** [CappyT/g14control#9]
By default, program starts with 'DEFAULT' plan, which does not exist. 
Would like everytime the plan changes (in addition to a notification), that it write the plan name to a data file (e.g. .currentplan), and when the program starts up, it tried to load that plan first, if not found then 'DEFAULT'.

This would allow it to persist between reboots.

**Comment by CappyT** [comment]
That was something I also thought, but rather than doing it in a dotfile, I would prefer to have a "last power plan" saved every time in the config file.
Also, I will probably need to save the "last AC plan" and "last DC plan" separately.

**Comment by carverhaines** [comment]
Sounds good

**Comment by carverhaines** [comment]
Alternatively, this may not be necessary if we implement automatic ac/dc switching. On app startup it would just first check current power state, and apply the default plan for DC or battery as proposed in: #8

**Comment by CappyT** [comment]
This would not solve the issue if the power plug is detached when the user has the app already running.

**Comment by carverhaines** [comment]
Only problem with saving it to the config file is could cause issues with versioning in git unless we are careful about resetting it to default every time.

If we get the AC/DC thing working, I don't think we need to remember between reboots:

IF default_ac_plan and default_dc_plan are null, then on start use 'default_starting_plan'
ELSE check call power_check() on start

**Comment by carverhaines** [comment]
I think PR #26 satisfies this for now.
Option of setting an initial plan on boot/start in config, or having it auto set based on power profile.
